
move:
  name: 'Move'
  description: 'Moves the camera.'
  target:
    entity:
      - integration: motioneye
      - domain: camera
  fields:
    direction:
      name: Direction
      example: 'UP'
      description: 'Select where to move the camera'
      required: true
      selector:
        select:
          mode: list
          options:
            - label: UP
              value: UP
            - label: DOWN
              value: DWON
            - label: RIGHT
              value: LEFT
            - label: LEFT
              value: RIGHT

create_preset:
  name: 'Create Preset'
  description: 'Creates Presets'
  target:
    entity:
      - integration: motioneye
      - domain: camera
  fields:
    preset_name:
      name: Preset Name
      example: 'Driveway'
      description: Sets a name for your preset.
      required: true
      selector:
        text:
    
    preset_position_x:
      name: Preset Position X
      example: '6'
      description: Sets the horizontal position of your camera
      required: true
      selector:
        number:
          mode: box
          min: 0
          max: 500

    preset_position_y:
      name: Preset Position Y
      example: '5'
      description: Sets the position of your preset in X and Y
      required: true
      selector:
        number:
          mode: box
          min: 0
          max: 500


go_to_preset:
  name: 'Go to Preset'
  description: 'Move camera to a predefined location'
  target:
    entity:
      - integration: motioneye
  fields:
    preset_name:
      name: Preset Name
      example: 'Driveway'
      description: 'Move camera to the predefined location'
      required: true
      selector:
        text:

add_camera_ptz:
  name: 'Add Camera'
  description: 'Adds your camera config to a file, for easier operation'
  target:
    entity:
      - integration: motioneye
      - domain: camera
  fields:
    protocol:
      name: Protocol
      example: 'TCP'
      description: Sets the ptz protocol
      required: true
      selector:
        select:
          mode: dropdown
          options:
            - 'TCP'
    onvif_method:
      name: Onvif Method
      example: 'ONVIF method'
      description: Sets some methods to move specific cameras (Other cameras can work, but no guarantee)
      required: false
      selector:
        select:
          mode: dropdown
          options:
            - 'YCC365'
            - 'Y05'
            - 'YOOSEE'
    host:
      name: Host
      example: '192.168.1.5'
      description: Type the ip of the camera without http, example 192.168.1.5
      required: true
      selector:
        text:

    port:
      name: Port
      example: '554'
      description: 'Type the port of the camera, example 554'
      required: true
      selector:
        text:

    x_steps:
      name: Steps X
      example: '12'
      description: 'The maximum number of moves your camera horizontally does (Needed for presets)'
      required: false
      selector:
        number:
          mode: box
          min: 0
          max: 500

    y_steps:
      name: Steps Y
      example: '10'
      description: 'The maximum number of moves your camera vertically does (Required for presets)'
      required: false
      selector:
        number:
          mode: box
          min: 0
          max: 500
clear_db:
  name: Clear Camera DB
  description: 'Deletes the file containing your ptz camera settings'
  target:
    entity:
      - integration: motioneye
      - domain: camera